# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


general:
  use_uvloop: true
# Uncomment the following to enable tracing. Run `phoenix serve` before launching
#  telemetry:
#    tracing:
#      phoenix:
#        _type: phoenix
#        endpoint: http://localhost:6006/v1/traces
#        project: simple_calculator

functions:
  calculator_multiply:
    _type: calculator_multiply
  calculator_inequality:
    _type: calculator_inequality
  calculator_divide:
    _type: nat_simple_calculator/calculator_divide
  current_datetime:
    _type: current_datetime
  calculator_subtract:
    _type: calculator_subtract
  react_agent:
    _type: tool_calling_agent
    tool_names:
      - calculator_multiply
      - calculator_inequality
      - current_datetime
      - calculator_divide
      - calculator_subtract
    llm_name: nim_mistral
    verbose: true
    handle_tool_errors: true

llms:
  nim_llm:
    _type: nim
    model_name: meta/llama-3.3-70b-instruct
    temperature: 0.0
    max_tokens: 1024
  nim_mistral:
    _type: nim
    model_name: nv-mistralai/mistral-nemo-12b-instruct
    temperature: 0.0
    max_tokens: 2000
  openai_llm:
    _type: openai
    model_name: gpt-3.5-turbo
    max_tokens: 2000
  r1_model:
    _type: nim
    model_name: deepseek-ai/deepseek-r1
    temperature: 0.0
    max_tokens: 2000

workflow:
  _type: reasoning_agent
  llm_name: r1_model
  augmented_fn: react_agent
  verbose: true
