# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

general:
  use_uvloop: true
  front_end:
    _type: fastapi
    cors:
      allow_origins: ["http://localhost:3000"]
      allow_headers: ["*"]
      allow_methods: ["*"]

functions:
  extract_por_tool:
    _type: extract_por_tool
    llm: extract_llm
    root_path: "./examples/HITL/por_to_jiratickets/data/"
  show_jira_tickets:
    _type: show_jira_tickets
    root_path: "./examples/HITL/por_to_jiratickets/data/"
  create_jira_tickets_tool:
    _type: create_jira_tickets_tool
    root_path: "./examples/HITL/por_to_jiratickets/data/"
    timeout: 20.0
    connect: 10.0
    jira_domain: ""
    jira_project_key: ""
    hitl_approval_fn: "hitl_approval_tool"
  get_jira_tickets_tool:
    _type: get_jira_tickets_tool
    root_path: "./examples/HITL/por_to_jiratickets/data/"
    jira_domain: ""
    jira_project_key: ""
  hitl_approval_tool:
    _type: hitl_approval_tool
    prompt: "I would like to create Jira tickets for the extracted data."

llms:
  extract_llm:
    _type: nim
    model_name: meta/llama-3.3-70b-instruct
    # model_name: "deepseek-ai/deepseek-r1"
    temperature: 0.0
    seed: 33
    max_tokens: 2000
  agent_llm:
    _type: nim
    # model_name: "deepseek-ai/deepseek-r1"
    # model_name: mistralai/mixtral-8x22b-instruct-v0.1
    model_name: meta/llama-3.3-70b-instruct
    temperature: 0.0
    seed: 33
    max_tokens: 2000

workflow:
  _type: react_agent
  llm_name: agent_llm
  tool_names:
    - extract_por_tool
    - show_jira_tickets
    - create_jira_tickets_tool
    - get_jira_tickets_tool
  verbose: true
